export const business = [
  {
    thumbnail: "https://play-lh.googleusercontent.com/2f5I8Qzu2kdkLtPYnpjYXG-_GLoGZEzbNE1qFzEdoDr9C4qAlNjxuo8Z3y0omklZug",
    name: "Taskade",
    description: "Một bộ não thứ hai cho đội ngũ kinh doanh của bạn. Một danh sách kỳ diệu để phân tách các vấn đề phức tạp và vẽ ra tư duy chung của bạn. Mở khóa trí tuệ đồng tác giả của bạn và kết nối các nhiệm vụ, ghi chú và nhóm trong một không gian làm việc thống nhất. Công cụ viết AI, ghi chú và tài liệu, nhiệm vụ và dự án, sơ đồ tư duy, trò chuyện video và nhiều hơn nữa.",
    link: "https://www.taskade.com/",
  },
  {
    thumbnail: "https://file.hstatic.net/200000489025/article/notion_la_gi__1__e921c36bf0474bebaf84f7589e92a6cf.png",
    name: "Notion all",
    description: "Tận dụng sức mạnh vô hạn của trí tuệ nhân tạo trong bất kỳ trang Notion nào. Viết nhanh hơn, nghĩ lớn hơn và tăng cường sự sáng tạo. Tất cả các wiki, tài liệu và dự án của bạn trong một nơi. Notion là không gian làm việc kết nối nơi công việc tốt hơn và nhanh hơn diễn ra.",
    link: "https://www.notion.so/",
  },
  {
    thumbnail: "https://ph-files.imgix.net/9b3f64d2-0ea3-4c2a-bf16-4876faa9ee83.png?auto=format",
    name: "Cody",
    description: "Trợ lý trí tuệ nhân tạo của bạn cho doanh nghiệp. Giống như ChatGPT, Cody là một trợ lý trí tuệ nhân tạo thông minh. Tuy nhiên, bạn có thể sử dụng cơ sở kiến thức của riêng mình để giảng dạy Cody về công ty, nhóm làm việc, quy trình và khách hàng của bạn. Sử dụng Cody để hỗ trợ đội ngũ của bạn, cung cấp hướng dẫn, hỗ trợ trong quá trình nảy ra ý tưởng, giải quyết vấn đề và cung cấp sự trợ giúp sáng tạo.",
    link: "https://meetcody.ai/",
  },
  {
    thumbnail: "https://media.licdn.com/dms/image/D4E0BAQFaTrGl9CRr6Q/company-logo_200_200/0/1688406645901?e=2147483647&v=beta&t=QxvN7IM3gAIgmspYI0LTqFig1j8J4c7D9laE9v9K7Sk",
    name: "Convolo",
    description: "Convolo là một trong những công cụ bán hàng tốt nhất cho doanh nghiệp. Cung cấp các công cụ giao tiếp giúp tăng doanh số bán hàng. Tăng cường ROI cho Chiến dịch Truyền đạt & Chiến dịch Gọi đi: Gọi từng khách hàng tiềm năng mới trong vòng một phút. Tiếp cận với nhiều Triển vọng hơn với Chiến dịch Gọi đi của bạn.",
    link: "https://convolo.ai/",
  },
  {
    thumbnail: "https://cdn-1.webcatalog.io/catalog/browse-ai/browse-ai-icon-filled-256.png?v=1675592820612",
    name: "Browse Al",
    description: "Trích xuất và giám sát dữ liệu trong vài giây với browse AI. Dễ dàng huấn luyện robot mà không cần mã code.",
    link: "https://www.browse.ai/",
  },
  {
    thumbnail: "https://ph-files.imgix.net/d74dbd7e-bf28-4668-96e0-e037844f8427.png?auto=format",
    name: "Orimon",
    description: "Tạo chatbot AI của riêng bạn chỉ trong vài phút. Tương tác với khán giả bằng khả năng gần như giống con người với trí tuệ hội thoại mạnh mẽ dành cho bán hàng. Hơn 120 ngôn ngữ. Được cung cấp bởi Oriserve, công nghệ trí tuệ hội thoại hàng đầu để nâng cao doanh số bán hàng, từ Google và chatGPT3 của OpenAI.",
    link: "https://orimon.ai/",
  },
  {
    thumbnail: "https://media.licdn.com/dms/image/D4D0BAQE2Feo_FHEuJw/company-logo_200_200/0/1667336262374?e=2147483647&v=beta&t=blCQde9Vc3avT_58T7fQven56jyAt6U0Z9Tm2SyzPDQ",
    name: "Repliq",
    description: "Thu hút nhiều cuộc họp hơn bằng cách thu hút khách hàng tiềm năng của bạn. Với video tùy chỉnh, bạn có thể tạo ra tác động lớn trong thời gian ngắn mà không phải làm phiền với việc tạo ra từng video riêng lẻ. RepliQ cho phép bạn cung cấp những thông điệp cá nhân hóa mang lại kết quả, đồng thời giúp bạn tương tác với khán giả trong các hoạt động tiếp cận lạnh một cách toàn diện, chỉ từ một hình ảnh sản phẩm duy nhất.",
    link: "https://www.repliq.co/",
  },
  {
    thumbnail: "https://yt3.googleusercontent.com/bvWhu_joXQ7zQO9mUH1jttq3lLTIXTI9gxNjnLrPUx4UBUWKDjmE7yj4nSXejwv791hQEm5t=s900-c-k-c0x00ffffff-no-rj",
    name: "Guidde ",
    description: "Giải thích các quy trình phức tạp nhất trong vài giây với tài liệu video do AI tạo ra. AI có thể tạo ra các hướng dẫn cách thực hiện tuyệt vời. AI có thể tạo ra các quy trình tiêu chuẩn hoạt động tuyệt vời. Guidde, nền tảng AI sinh sáng cho doanh nghiệp, giúp đội ngũ của bạn tạo ra tài liệu video nhanh hơn 11 lần.",
    link: "https://www.guidde.com/",
  },
  {
    thumbnail: "https://gdm-catalog-fmapi-prod.imgix.net/ProductLogo/303829c0-8885-45cb-82f9-ce5e0d90b40b.png",
    name: "BotNation",
    description: "Botnation.ai là nền tảng AI trò chuyện cuối cùng cho phép doanh nghiệp xây dựng và triển khai chatbot thông minh một cách dễ dàng. Công nghệ xử lý ngôn ngữ tự nhiên tiên tiến và giao diện người dùng thân thiện giúp doanh nghiệp tạo ra trải nghiệm trò chuyện hấp dẫn và cá nhân hóa cho khách hàng của mình. Cho dù bạn đang tìm cách cải thiện dịch vụ khách hàng, tăng tỷ lệ chuyển đổi hoặc tối ưu hóa quy trình, Botnation.ai có tất cả những gì bạn cần để thành công trong lĩnh vực trí tuệ hội thoại.",
    link: "https://botnation.ai/",
  },
  {
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDA0UHtPriidLZZ4qTaXhfXIlLE0UGH_K0D1Ybl6TBjfpk1IegvJOW8x3XHFCf-HVg60Q&usqp=CAU",
    name: "Hiver",
    description: "Hỗ trợ khách hàng dễ dàng với trí tuệ nhân tạo. Cung cấp hỗ trợ nhanh chóng và cá nhân hóa. Chạy phần mềm từ bên trong Gmail.",
    link: "https://hiver.referralrock.com/",
  },
  {
    thumbnail: "https://play-lh.googleusercontent.com/3XarjB7-NPvRWLY8qqX4mpkhSxjF4vuyz1-MJexuIpt79hW1ImdqP7M2wS-IEsnl2qI",
    name: "Otter Al",
    description: "Ghi lại và chia sẻ những hiểu biết từ cuộc họp. Otter ghi lại cuộc họp, ghi chú ngay lập tức và tạo ra một bản tóm tắt tự động để chia sẻ với mọi người và giúp bạn ghi nhớ mọi thứ.",
    link: "https://otter.ai/",
  },
  {
    thumbnail: "https://uploads-ssl.webflow.com/63744cb0fa1468f8519ecaf7/63be21b317f71c50b934017b_Humana%20Logo%20256px.png",
    name: "Humata",
    description: "Tải lên một tệp PDF và nhận câu trả lời từ đó. Tạo Báo cáo Nhanh Gấp 100 lần. Hiểu Tài liệu Kỹ thuật Nhanh Gấp 100 lần. Phân tích Tài liệu Pháp lý Nhanh Gấp 100 lần.",
    link: "https://www.humata.ai/",
  },
  {
    thumbnail: "https://yt3.googleusercontent.com/xXACh1duL8LK4KruS54DRUaPQL2nBjZpPmEJ_9G_qhIDgtnqPyhHdryqhHcLadqpQMbXQ5AOiw=s900-c-k-c0x00ffffff-no-rj",
    name: "Sheet Al",
    description: "Có sẵn cho Google Sheets và Excel (Sắp ra mắt). Bỏ qua việc học tập và bắt đầu làm việc ngay. Sử dụng trí tuệ nhân tạo để chuyển đổi hướng dẫn văn bản của bạn thành công thức Google Sheet một cách nhanh chóng. (Sẽ ra mắt trong 2-3 tuần tới).",
    link: "https://www.sheetai.app/",
  },
  {
    thumbnail: "https://www.dimeadozen.ai/assets/logo_clearimg-7697c3b6.png",
    name: "DimeADizon",
    description: "Xác minh ý tưởng kinh doanh dựa trên trí tuệ nhân tạo. Đối với bất kỳ startup nào, nghiên cứu thị trường do trí tuệ nhân tạo hỗ trợ. Tận dụng trí tuệ nhân tạo để nhanh chóng khám phá cách công ty của bạn có thể phát triển và làm thế nào để thâm nhập vào bất kỳ ngành nghề nào.",
    link: "https://www.dimeadozen.ai/",
  },
  {
    thumbnail: "https://media.licdn.com/dms/image/C4E0BAQHwxK4RlFBRNw/company-logo_200_200/0/1576848285487?e=2147483647&v=beta&t=xLK6rfgI2jIHRTETMAEKk6XwLpOZDz0_YpqA4VqVzL4",
    name: "Ideabuddy",
    description: "Biến ý tưởng kinh doanh của bạn thành hiện thực. Phần mềm quản lý kế hoạch kinh doanh toàn diện giúp bạn biến ý tưởng tuyệt vời của mình thành một doanh nghiệp thành công.",
    link: "https://ideabuddy.com/",
  },
  {
    thumbnail: "https://ps.w.org/play-ht/assets/icon-256x256.png?rev=1810827",
    name: "Play.ht",
    description: "Máy tạo giọng nói dựa trên trí tuệ nhân tạo. Tạo âm thanh chuyển văn bản thành giọng nói (TTS) thực tế bằng cách sử dụng Trình tạo giọng AI trực tuyến của chúng tôi và các giọng nói tổng hợp tốt nhất. Chuyển đổi văn bản thành giọng nói tự nhiên ngay lập tức và tải xuống dưới dạng tệp âm thanh MP3 và WAV.",
    link: "https://play.ht/",
  },
];
