export const SEO = [
  {
    thumbnail: "https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_27c8995b551f0fa9032f75c10fe1aa59/surfer-surfer.png",
    name: "SurferSEO",
    description: "SurferSEO là một trong những công cụ SEO tốt nhất để viết nội dung tối ưu hóa SEO tuyệt vời. Nó sẽ chỉ cho bạn những gì cần bao gồm trong các bài viết, từ khoá tốt nhất, điểm số SEO hiện tại và cách cải thiện, và đảm bảo mỗi bài viết đều được tối ưu hóa SEO và chất lượng hàng đầu. Có thể dùng thử miễn phí.",
    link: "https://surferseo.com/",
  },
  {
    thumbnail: "https://cdn.semrush.com/__static__/semrush-logo-700.jpg",
    name: "Semrush",
    description: "Tận dụng tiếp thị internet để đạt được kết quả có thể đo lường. Sử dụng một công cụ duy nhất để thực hiện SEO, tiếp thị nội dung, phân tích đối thủ, PPC và tiếp thị truyền thông xã hội.",
    link: "https://www.semrush.com/",
  },
  {
    thumbnail: "https://morningscore.io/wp-content/uploads/2019/11/morningscore-logo-square.jpg",
    name: "Morning Score",
    description: "Morningscore là một trong những công cụ SEO toàn diện tốt nhất hiện có. Dễ dàng sửa chữa sức khỏe trang web của bạn và tối ưu hóa SEO cùng xếp hạng với công cụ SEO chơi game của họ.",
    link: "https://morningscore.io",
  },
  {
    thumbnail: "https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_f8f324101efad07fbbf0f0272bfe0cb9/jasper-ai.jpg",
    name: "Jasper AI",
    description: "Tạo ra các bài viết blog, nghệ thuật và hình ảnh tuyệt vời, bản sao tiếp thị, email bán hàng, nội dung SEO, quảng cáo Facebook, nội dung web, chú thích, kịch bản video nhanh hơn 10 lần với trí tuệ nhân tạo. Jasper là Trình tạo nội dung AI giúp bạn và đội ngũ của bạn vượt qua những trở ngại sáng tạo để tạo ra nội dung tuyệt vời, độc đáo nhanh hơn 10 lần.",
    link: "https://www.jasper.ai/",
  },
  {
    thumbnail: "https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_368da0671427a82c6e405a0dcbaa9b2c/getgenie-ai.jpg",
    name: "GETgenie",
    description: "GETgenie là trợ lý SEO AI toàn diện của bạn. Bằng cách tập trung tất cả khả năng bạn cần vào một ứng dụng WordPress duy nhất, GetGenie AI hoạt động như ma thuật, tiết kiệm thời gian và tiền bạc cho bạn so với việc sử dụng 10+ công cụ khác. Vượt qua đối thủ với nghiên cứu cạnh tranh SERP và tối ưu hóa trò chơi SEO của bạn. Các bài viết blog và bản sao tiếp thị được hỗ trợ bởi trí tuệ nhân tạo, tận dụng cơ hội SEO với phân tích từ khóa SEO được hỗ trợ bởi trí tuệ nhân tạo. ",
    link: "https://getgenie.ai/",
  },
  {
    thumbnail: "https://images.crunchbase.com/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/ci8hv3dncoavlcwjh0g8",
    name: "Write Sonic",
    description: "WriteSonic.com là một công cụ hỗ trợ viết hiện đại sử dụng công nghệ trí tuệ nhân tạo tiên tiến giúp bạn viết tốt hơn, nhanh hơn và hiệu quả hơn. Với các tính năng như tự động diễn đạt lại, phân tích ngữ điệu và gợi ý thời gian thực, WriteSonic.com đưa việc viết của bạn lên một tầm cao mới.",
    link: "https://writesonic.com/",
  },
  {
    thumbnail: "https://ph-files.imgix.net/787f47c7-7c5c-4ab6-9ecf-9163b8bf6cf7.png?auto=format",
    name: "Sincode",
    description: "SinCode làm cho nội dung viết bằng trí tuệ nhân tạo của bạn trở nên gần gũi hơn để bạn không bị đánh giá tiêu cực từ Google. SinCode sẽ giúp bạn tăng cường SEO và tất cả các loại nội dung viết. Tạo nội dung tối ưu hóa SEO không vi phạm bản quyền cho blog, bài viết, trang web, email và tất cả các loại nội dung viết nhanh hơn 10 lần.",
    link: "https://www.sincode.ai/",
  },
  {
    thumbnail: "https://images.g2crowd.com/uploads/product/image/social_landscape/social_landscape_9890658010fc40665571b477745a99b5/ink-for-all.png",
    name: "Ink for all",
    description: "Tiếp cận Marketing Nội dung AI mà không ảnh hưởng tiêu cực đến thương hiệu của bạn. Nội dung AI đang bị nghiêm cấm một cách nghiêm ngặt bởi Google và các trang web khác. INK for all có thể phát hiện nó. Hiện có một Nền tảng Nội dung AI toàn diện đã ưu tiên an ninh.",
    link: "https://inkforall.com/",
  },
  {
    thumbnail: "https://pbs.twimg.com/profile_images/1366461794504613888/K-zV4rJm_400x400.png",
    name: "CTRify",
    description: "Nền tảng Thực hiện SEO đầu tiên được trang bị trí tuệ nhân tạo. Tạo các trang web xếp hạng trên Google chỉ bằng cách cung cấp một từ khoá cho Trí tuệ nhân tạo. Nâng cao thứ hạng SERPs, tỷ lệ nhấp vào tự nhiên, thời gian lưu trú và Pogo Sticking nhờ lưu lượng truy cập tự nhiên từ hàng triệu thiết bị máy tính để bàn và di động kết nối từ các địa điểm IP cư trú của các nhà mạng di động hàng đầu từ tất cả các vị trí trên thế giới.",
    link: "https://www.ctrify.com/",
  },
  {
    thumbnail: "https://seovendor.co/wp-content/uploads/2019/02/logo_black.png",
    name: "SEO GPT",
    description: "Chỉ có một công cụ AI SEO độc quyền với 10 lần hiệu quả vượt trội dành cho nhãn trắng trên thế giới. Nền tảng White Label SEO, PPC và Website Reseller miễn phí. Đăng ký để truy cập hơn 30 dịch vụ tiếp thị, các công cụ miễn phí, quy trình bán hàng, PPC và tạo trang web.",
    link: "https://seovendor.co/",
  },
  {
    thumbnail: "https://yt3.googleusercontent.com/WETI5uqYhGrWCpSxIMhBYgMhM0Mp2uhE4NjxatkSJv2dmSMWaoecrF1WEEwDiXM5I3NIkLvbbw=s900-c-k-c0x00ffffff-no-rj",
    name: "Copy AI",
    description: "Copy.ai cung cấp cách nhanh nhất và hiệu quả nhất để tạo ra nội dung chất lượng cao. Copy.ai tạo ra nội dung thu hút độc giả và chuyển đổi họ trong khi tiết kiệm thời gian và tiền bạc nhờ công nghệ trí tuệ nhân tạo tiên tiến.",
    link: "https://www.copy.ai/",
  },
  {
    thumbnail: "https://nachonacho.com/_next/image?url=https%3A%2F%2Ffiles.nachonacho.com%2Fusers%2Fcl12m0wwr136122epmu7ds49cn8%2Fnn_1680887799116_icon_256x256.png&w=256&q=75",
    name: "Kafkai",
    description: "Kafkai là một thuật toán học máy có thể viết các bài viết từ đầu. Công nghệ tiên tiến dành cho nhà tiếp thị và chuyên gia SEO.",
    link: "https://kafkai.com/",
  },
  {
    thumbnail: "https://www.spinrewriter.com/images/spin-rewriter-10-box-3d.png",
    name: "Spinrewriter",
    description: "Nhận nội dung duy nhất với Spinrewriter. Xem cách viết lại một bài viết thành 500 bài viết chỉ trong 45 giây. Với công nghệ ENL, Spin Rewriter là công cụ hoàn hảo cho các chuyên gia SEO cần nội dung duy nhất và chất lượng con người để đạt thứ hạng cao trên Google.",
    link: "https://www.spinrewriter.com/free/summer-sale",
  },
  {
    thumbnail: "https://images.crunchbase.com/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/e1dskr6gsv0emgnt7wsx",
    name: "Longshot",
    description: "Tạo blog mà cả con người và các công cụ tìm kiếm đều yêu thích bằng Trí tuệ nhân tạo. LongShot là trợ lý viết AI giúp bạn và nhóm của bạn tạo ra các blog hữu ích được xếp hạng trên Google.",
    link: "https://www.longshot.ai",
  },
  {
    thumbnail: "https://typli.ai/51674fbb83614544fdff6e2780102b64.png",
    name: "Typli",
    description: "Công cụ Nội dung Trí tuệ nhân tạo hiển nhiên nhất kết hợp viết AI và Trợ lý SEO.",
    link: "https://typli.ai/",
  },
  {
    thumbnail: "https://growthbarseo.com/wp-content/uploads/2021/06/1200px-G2_Crowd_logo.svg_-995x1024.png",
    name: "Growthbar SEO",
    description: "Viết nội dung hoàn hảo thân thiện với SEO cho bài viết blog, trang web và bài viết bằng Trí tuệ nhân tạo. Tạo nội dung mà Google yêu thích chỉ trong chốc lát.",
    link: "https://www.growthbarseo.com",
  },
  {
    thumbnail: "https://storage.googleapis.com/shineranker-prod-storage/assets/img/logo/logo-white.png",
    name: "Shine Ranker",
    description: "Công cụ Nghiên cứu Từ khóa và Kiểm tra trang web. Shine Ranker là công cụ kiểm tra trang web và nghiên cứu từ khóa SEO giúp đưa trang web của bạn lên hàng đầu trên Google và kiếm tiền từ đó.",
    link: "https://chasereiner.thrivecart.com/",
  },
  {
    thumbnail: "https://mangools.com/assets/app-logos/mangools-logo-full-80efddbf1742056da96d41bc32407c96b709655e19b2d5ca7df98adcfd605e8b.svg",
    name: "Mangools",
    description: "Mangools là công cụ SEO tuyệt vời để tìm kiếm từ khóa tốt nhất, SERP cho bất kỳ địa điểm nào, xếp hạng, liên kết đối thủ và theo dõi đối thủ.",
    link: "https://mangools.com/",
  },
  {
    thumbnail: "https://media.licdn.com/dms/image/C4D0BAQEciPDUjAaQeQ/company-logo_200_200/0/1652788733457?e=2147483647&v=beta&t=w3R6DAGYxMrFeuvM8OKbGrWO1EvMtz_sAuI4bgB4-Bg",
    name: "Rankranger",
    description: "Đẩy mạnh tăng trưởng tự nhiên với sự trợ giúp từ công cụ SEO All-in-One này. Công cụ SEO chuyên nghiệp cung cấp những thông tin độc đáo, phân tích đối thủ và theo dõi tiến độ không giới hạn.",
    link: "http://www.rankranger.com/",
  },
  {
    thumbnail: "https://progsoft.net/images/serpstat-icon-bd9509b9a6e7e94efc270efd9891135b62c86c37.png",
    name: "Serpstat",
    description: "Serpstat là một trong những công cụ growth hacking tốt nhất cho SEO, Marketing, PPC và nhiều lĩnh vực khác. Tối ưu hóa SEO với Serpstat.",
    link: "https://serpstat.com/",
  },
  {
    thumbnail: "https://seranking.com/wp-content/uploads/sites/9/2019/07/og-image.png",
    name: "SE Ranking",
    description: "SEranking là công cụ SEO toàn diện của bạn. Theo dõi xếp hạng từ khóa chính xác, phân tích đối thủ PPC/SEO, kiểm tra và giám sát liên kết trở lại (backlink), thực hiện kiểm tra website (audit) và rất nhiều chức năng khác.",
    link: "https://seranking.com/",
  },
  {
    thumbnail: "https://ps.w.org/link-whisper/assets/icon-256x256.png?rev=2242818",
    name: "Link Whisper",
    description: "LinkWhisper giúp bạn xây dựng liên kết nội bộ. Đơn giản và hiệu quả để xây dựng liên kết nội bộ và tối ưu hóa SEO.",
    link: "https://linkwhisper.com/",
  },
  {
    thumbnail: "https://rankmath.com/wp-content/uploads/2022/08/rank-math-logo-square.png",
    name: "Rankmath",
    description: "RankMath là một plugin WordPress mạnh mẽ cho SEO. Tối ưu hóa nội dung của bạn với các gợi ý tích hợp và các quy tắc tốt nhất về SEO. Được đề xuất bởi một số phần mềm SEO tốt nhất.",
    link: "https://rankmath.com/",
  },
];
